lib/faux_banker/account_requests/router.ex
defmodule FauxBanker.AccountRequests.Router do
  use Commanded.Commands.CompositeRouter

  alias FauxBanker.AccountRequests, as: Context

  router(Context.Requests.Router)
end

lib/faux_banker/bank_accounts/router.ex
defmodule FauxBanker.BankAccounts.Router do
  use Commanded.Commands.CompositeRouter

  alias FauxBanker.BankAccounts, as: Context

  router(Context.Accounts.Router)
end

lib/faux_banker/router.ex
defmodule FauxBanker.Router do
  use Commanded.Commands.CompositeRouter

  router(FauxBanker.AccountRequests.Router)
  router(FauxBanker.BankAccounts.Router)
end

lib/faux_banker_web/router.ex
defmodule FauxBankerWeb.Router do
  use FauxBankerWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :browser_auth do
    plug(Guardian.Plug.Pipeline,
      module: FauxBanker.Guardian,
      error_handler: FauxBankerWeb.AuthErrorHandler
    )

    plug(Guardian.Plug.VerifySession)
    plug(Guardian.Plug.EnsureAuthenticated)
    plug(Guardian.Plug.LoadResource)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/", FauxBankerWeb do
    pipe_through(:browser)

    get("/registration", AuthController, :register_client_form)
    post("/registration", AuthController, :register_client)

    get("/signin", AuthController, :signin_form)
  end

  scope "/", FauxBankerWeb do
    pipe_through([:browser, :browser_auth])

    get("/", HomeController, :home_screen)

    scope "/clients" do
      get("/:code", ManagerController, :view_screen)
      get("/:code/open_account", ManagerController, :open_account_screen)
      post("/:code/open_account", ManagerController, :open_account)
    end

    scope "/accounts" do
      get("/:code", ClientController, :view_screen)
      get("/:code/withdraw", ClientController, :withdraw_screen)
      post("/:code/withdraw", ClientController, :withdraw)

      get("/:code/deposit", ClientController, :deposit_screen)
      post("/:code/deposit", ClientController, :deposit)
    end

    scope "/requests" do
      get("/", ClientController, :make_request_screen)
      post("/", ClientController, :make_request)

      get("/:code/approve", ClientController, :approve_request_screen)
      post("/:code/approve", ClientController, :approve_request)

      get("/:code/reject", ClientController, :reject_request_screen)
      post("/:code/reject", ClientController, :reject_request)
    end
  end

  scope "/auth", FauxBankerWeb do
    pipe_through(:browser)

    get("/:provider", AuthController, :request)
    post("/identity/callback", AuthController, :callback)
    get("/:provider/callback", AuthController, :callback)
    delete("/logout", AuthController, :signout)
  end

  if Mix.env() == :dev do
    forward("/sent_emails", Bamboo.EmailPreviewPlug)
  end
end

lib/faux_banker_web/views/layout_view.ex
defmodule FauxBankerWeb.LayoutView do
  use FauxBankerWeb, :view
end

lib/faux_banker_web/templates/layout/alert.html.eex
<%= if get_flash(@conn, :info) do %>
<div class='alert alert-info' role='alert'>
  <%= get_flash(@conn, :info) %>
</div>
<% end %>
<%= if get_flash(@conn, :error) do %>
<div class='alert alert-danger' role='alert'>
  <%= get_flash(@conn, :error) %>
</div>
<% end %>

lib/faux_banker_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Faux Banker</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container-fluid p-0">
      <%= render @view_module, @view_template, assigns %>
    </div>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/faux_banker_web/templates/layout/header.html.eex
<nav class='navbar navbar-expand-lg navbar-dark bg-primary'>
  <a class='navbar-brand' href='/'>Faux Bank</a>

  <ul class='navbar-nav'>
    <li class='nav-item'>
      <span class='navbar-text'>
        <%= @user.email %>
      </span>
    </li>
    <li class='nav-item'>
      <%= form_tag auth_path(@conn, :signout), method: "delete" do %>
      <button class='btn btn-primary'>
        Logout
      </button>
      <% end %>
    </li>
  </ul>
</nav>