lib/faux_banker/account_requests/router.ex
defmodule FauxBanker.AccountRequests.Router do
  use Commanded.Commands.CompositeRouter

  alias FauxBanker.AccountRequests, as: Context

  router(Context.Requests.Router)
end

lib/faux_banker/bank_accounts/router.ex
defmodule FauxBanker.BankAccounts.Router do
  use Commanded.Commands.CompositeRouter

  alias FauxBanker.BankAccounts, as: Context

  router(Context.Accounts.Router)
end

lib/faux_banker/router.ex
defmodule FauxBanker.Router do
  use Commanded.Commands.CompositeRouter

  router(FauxBanker.AccountRequests.Router)
  router(FauxBanker.BankAccounts.Router)
end

lib/faux_banker_web/router.ex
defmodule FauxBankerWeb.Router do
  use FauxBankerWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :browser_auth do
    plug(Guardian.Plug.Pipeline,
      module: FauxBanker.Guardian,
      error_handler: FauxBankerWeb.AuthErrorHandler
    )

    plug(Guardian.Plug.VerifySession)
    plug(Guardian.Plug.EnsureAuthenticated)
    plug(Guardian.Plug.LoadResource)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/", FauxBankerWeb do
    pipe_through(:browser)

    get("/registration", AuthController, :register_client_form)
    post("/registration", AuthController, :register_client)

    get("/signin", AuthController, :signin_form)
  end

  scope "/", FauxBankerWeb do
    pipe_through([:browser, :browser_auth])

    get("/", HomeController, :home_screen)

    scope "/clients" do
      get("/:code", ManagerController, :view_screen)
      get("/:code/open_account", ManagerController, :open_account_screen)
      post("/:code/open_account", ManagerController, :open_account)
    end

    scope "/accounts" do
      get("/:code", ClientController, :view_screen)
      get("/:code/withdraw", ClientController, :withdraw_screen)
      post("/:code/withdraw", ClientController, :withdraw)

      get("/:code/deposit", ClientController, :deposit_screen)
      post("/:code/deposit", ClientController, :deposit)
    end

    scope "/requests" do
      get("/", ClientController, :make_request_screen)
      post("/", ClientController, :make_request)

      get("/:code/approve", ClientController, :approve_request_screen)
      post("/:code/approve", ClientController, :approve_request)

      get("/:code/reject", ClientController, :reject_request_screen)
      post("/:code/reject", ClientController, :reject_request)
    end
  end

  scope "/auth", FauxBankerWeb do
    pipe_through(:browser)

    get("/:provider", AuthController, :request)
    post("/identity/callback", AuthController, :callback)
    get("/:provider/callback", AuthController, :callback)
    delete("/logout", AuthController, :signout)
  end

  if Mix.env() == :dev do
    forward("/sent_emails", Bamboo.EmailPreviewPlug)
  end
end

lib/faux_banker_web/controllers/home_controller.ex
defmodule FauxBankerWeb.HomeController do
  @moduledoc false

  use FauxBankerWeb, :controller

  alias FauxBanker.Guardian

  def home_screen(conn, _params) do
    render(conn, "home.html", user: Guardian.Plug.current_resource(conn))
  end
end

lib/faux_banker_web/views/home_view.ex
defmodule FauxBankerWeb.HomeView do
  use FauxBankerWeb, :view

  alias FauxBanker.{BankAccounts, Clients, AccountRequests}

  def clients(),
    do: Clients.list_clients()

  def bank_accounts(client_id),
    do: BankAccounts.list_accounts_by_client_id(client_id)

  def friends(client_id),
    do: Clients.list_client_friends_by_id(client_id)

  def requests(client_id),
    do: AccountRequests.list_client_requests_by_client_id(client_id)
end

lib/faux_banker_web/templates/home/client_home.html.eex
<div class='container-fluid p-3'>
  <p class='h3'>Accounts</p>

  <table class='table table-sm table-striped table-hover p-3'>
    <thead class='thead-dark'>
      <tr>
        <th scope='col'>#</th>
        <th scope='col'>Account</th>
        <th scope='col'>Balance</th>
        <th scope='col'>Actions</th>
      </tr>
    </thead>
    <tbody>
      <%= for account <- bank_accounts(@user.id) do %>
          <tr>
            <td>
              <%= account.code %>
            </td>
            <td>
              <%= account.name %>
            </td>
            <td>
              <%= Decimal.round(account.balance, 2) %>
            </td>
            <td>
              <a href='<%= client_path(@conn, :view_screen, account.code)
                           %>' class='btn btn-secondary btn-md active'
                 role='button' aria-pressed='true'>
                View
              </a>
            </td>

          </tr>
          <% end %>
    </tbody>
  </table>
</div>

<div class='container-fluid p-3'>
  <p class='h3'>Friends</p>

  <table class='table table-sm table-striped table-hover p-3'>
    <thead class='thead-dark'>
      <tr>
        <th scope='col'>Name</th>
      </tr>
    </thead>
    <tbody>
      <%= for friend <- friends(@user.id) do %>
          <tr>
            <td>
              <%= friend.first_name <> " " <> friend.last_name %>
            </td>
          </tr>
          <% end %>
    </tbody>
  </table>
</div>

<div class='container-fluid p-3'>
  <p class='h3'>Requests</p>

  <a href='<%= client_path(@conn, :make_request_screen) %>' class='btn btn-primary m-1' tabindex='-1' role='button'
     aria-disabled='true'>
    Make Request
  </a>

  <table class='table table-sm table-striped table-hover p-3'>
    <thead class='thead-dark'>
      <tr>
        <th scope='col'>Date/Time</th>
        <th scope='col'>#</th>
        <th scope='col'>Status</th>
        <th scope='col'>Type</th>
        <th scope='col'>Account</th>
        <th scope='col'>Reason</th>
        <th scope='col'>Amount</th>
        <th scope='col'>Response</th>
        <th scope='col'>Actions</th>
      </tr>
    </thead>
    <tbody>
      <%= for request <- requests(@user.id) do %>
          <tr>
            <td>
              <%= Timex.format!(Timex.local(request.updated_at), "%F %T", :strftime) %>
            </td>
            <td>
              <%= request.code %>
            </td>
            <td>
              <%= String.upcase(Atom.to_string(request.status)) %>
            </td>
            <td>
              <%= if @user.id == request.sender_id do %>
              SENDER
              <% else %>
              RECEIPIENT
              <% end %>
            </td>
            <td>
              <%= request.sender_account.name %>
            </td>
            <td>
              <%= request.sender_reason %>
            </td>
            <td>
              <%= Decimal.round(request.amount, 2) %>
            </td>
            <td>
              <%= request.receipient_reason %>
            </td>
            <td>
              <%= if request.status == :pending and @user.id == request.receipient_id do %>
              <a href='<%= client_path(@conn, :approve_request_screen, request.code)
                           %>' class='btn btn-primary btn-md active'
                 role='button' aria-pressed='true'>
                Approve
              </a>
              <a href='<%= client_path(@conn, :reject_request_screen, request.code)
                           %>' class='btn btn-secondary btn-md active'
                 role='button' aria-pressed='true'>
                Reject
              </a>
              <% end %>
            </td>
          </tr>
          <% end %>
    </tbody>
  </table>
</div>

lib/faux_banker_web/templates/home/home.html.eex
<%= render FauxBankerWeb.LayoutView, "header.html", assigns %>
<%= render FauxBankerWeb.LayoutView, "alert.html", assigns %>

<%= if @user.role == :manager do %>
  <%= render "manager_home.html", assigns %>
<% end %>

<%= if @user.role == :client do %>
  <%= render "client_home.html", assigns %>
<% end %>

lib/faux_banker_web/templates/home/manager_home.html.eex
<div class='container-fluid p-3'>
  <p class='h3'>Clients</p>

  <table class='table table-sm table-striped table-hover p-3'>
    <thead class='thead-dark'>
      <tr>
        <th scope='col'>Client</th>
        <th scope='col'>Actions</th>
      </tr>
    </thead>
    <tbody>
      <%= for client <- clients() do %>
          <tr>
            <td>
              <%= client.first_name <> " " <> client.last_name %>
            </td>
            <td>
              <a href='<%= manager_path(@conn, :view_screen, client.code)
                           %>' class='btn btn-secondary btn-md active'
                 role='button' aria-pressed='true'>
                View
              </a>
            </td>
          </tr>
          <% end %>
    </tbody>
  </table>
</div>